language: ruby
rvm:
  - 1.9.3
  # - jruby-18mode # JRuby in 1.8 mode
  # - jruby-19mode # JRuby in 1.9 mode
# script:
# 	- RAILS_ENV=test bundle exec rake ci --trace db:create
# 	- RAILS_ENV=test bundle exec rake ci --trace db:migrate
env:
  - DB=mysql
script:
    - RAILS_ENV=test bundle exec rake db:migrate --trace
    - bundle exec rake db:test:prepare
    - bundle exec rake
before_script:
    - mysql -e 'create database forum_test'
notifications:
    email:
        - satbirdd@gmail.com